#!perl

use 5.010;
use strict;
use warnings;

use Getopt::Long qw(:config bundling no_ignore_case auto_help auto_version);
use Test::Regexp::Pattern;

# AUTHORITY
# DATE
# DIST
# VERSION

my %opts = (
    #exclude_packages => [],
    test_examples => 1,
);
GetOptions(
    #'exclude-package=s' => $opts{exclude_packages},
    #'exclude-function=s' => $opts{exclude_functions},
    'E' => sub { $opts{test_examples} = 0 },
);

regexp_patterns_in_all_modules_ok(
    \%opts,
);

1;
# ABSTRACT: Test Regexp::Pattern patterns in all modules of your distro
# PODNAME:

=head1 SYNOPSIS

In your distro directory:

 % test-regexp-pattern [options]


=head1 DESCRIPTION

This script is a command-line interface for L<Test::Regexp::Pattern>'s
C<regexp_patterns_in_all_modules_ok()> function.


=head1 OPTIONS

=over

=item * -E

This sets C<test_examples> to 0.

=back


=head1 SEE ALSO

L<Test::Regexp::Pattern>

=cut
